### ISSUE TITLE
new.apk、old.apk在根目录，但是demo crash

### ISSUE THREAD

**Issue by fldroid** [eleme/bspatch#2]
Process: me.ele.bspatch.demo, PID: 9564
                                                                   java.lang.IllegalArgumentException: oldApkPath /storage/emulated/0/old.apk cannot be read, please check
                                                                       at me.ele.bspatch.Patcher.work(Patcher.java:29)
                                                                       at me.ele.bspatch.demo.MainActivity$1.run(MainActivity.java:31)

**Comment by JackCho** [comment]
your devices may be above Android M 6.0, please check your `WRITE_EXTERNAL_STORAGE` permission is granted or not
